# Generated by Django 3.2.8 on 2021-11-27 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20211110_2040'),
        ('mainapp', '0003_productcategory_name'),
    ]

    operations = [
    ]
